# Local Developer Configuration Overrides
server.port=8089
payments.cybersource.merchant-id=local_dev_merchant_123
payments.cybersource.api-key=local_dummy_key_xyz
payments.cybersource.sandbox-mode=true

# H2 Database Connection Settings
spring.datasource.url=jdbc:h2:mem:paymenthub_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=secure_dev_pass

# JPA/Hibernate Diagnostic Logging Layouts
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable visual browser console to check our tables live
spring.h2.console.enabled=true

# CyberSource Payment Gateway Sandbox Environment Profiles
cybersource.base-url=https://apitest.cybersource.com
cybersource.merchant-id=teczaleel_sandbox_merchant_67
cybersource.api-key-id=0829a1b4-4fac-4299-881c-901b089bfa88
cybersource.api-secret-key=v3ryS3cr3tK3yStr1ngTh4tSh0uldN3v3rB3Exposed12345=

# Mock mode: bypasses real CyberSource calls and simulates gateway responses
cybersource.mock-enabled=true

