# QA / Sandbox Environment Configuration
server.port=8082
payments.cybersource.merchant-id=v_sandbox_merchant_999
payments.cybersource.api-key=sb_secure_live_simulated_key_777
payments.cybersource.sandbox-mode=true